#!/usr/bin/env node
/**
 * semantic-cache.mjs
 *
 * Deterministic on-demand semantic cache mechanics (openspec: changes/
 * hybrid-retrieval, capability `semantic-cache`, design D5). This module
 * calls NO model — the summary/tags CONTENT is generated by the chat (model
 * side) and merely PASSED IN here; this file only decides whether a write is
 * allowed (field whitelist plus canonical-language gate), whether a cached
 * entry is still fresh (cache schema/language identity plus hash comparison
 * against `source-manifest.json`), and safely commits a write under a
 * short-held lock with compare-and-swap against the node's current source
 * hash.
 *
 * Persistence: `.excavator/semantic-cache.json` (entries keyed by node id —
 * the SAME node-identity authority node-identity.mjs / build-fact-graph.mjs /
 * build-source-index.mjs already use, so a chat-cached summary and a
 * source-index/fact-graph node line up under one id) and a shared
 * `.excavator/semantic.lock` (`{pid, host, acquiredAt}`), held only briefly
 * around the commit (design D5: "locks only coordinate writes, not
 * generation" — an occasional duplicate recompute across two racing chats is
 * accepted rather than holding a lock across the slow, model-driven part).
 *
 * Source freshness/CAS is hash-based against `source-manifest.json`'s
 * per-file `contentHash` (equal -> reuse, missing -> not generated, differ ->
 * stale/ignore), while semantic trust additionally requires the current
 * cache schema and `contentLanguage: "en"`. This is a deliberate
 * simplification of design D5's prose ("reread the latest
 * manifest + fact graph + cache"): this system tracks no hash finer-grained
 * than a whole file's content hash, so "the node's current source hash" IS
 * the containing file's manifest entry — there is no separate fact-graph
 * hash to compare against, and re-reading the (potentially large)
 * `knowledge-graph.json` on every commit would add cost without adding a
 * distinct freshness signal. This module therefore never reads
 * `knowledge-graph.json` at all, which also makes the "chat semantic writes
 * MUST NEVER modify knowledge-graph.json" guarantee trivially true by
 * construction rather than merely tested.
 *
 * A commit failure (lock contention, a stale CAS hash, a rejected field, or
 * any I/O error) returns a status object; this module NEVER throws, so a
 * cache write can never block a chat answer (spec Requirement "concurrency-
 * safe write, fact layer read-only", Scenario "a cache commit failure does
 * not block the answer").
 *
 * Contract: openspec/changes/hybrid-retrieval/specs/semantic-cache/spec.md
 */

import { hostname } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  existsSync, mkdirSync, readFileSync, writeFileSync, renameSync,
  openSync, writeSync, closeSync, unlinkSync,
} from 'node:fs';
import { createRequire } from 'node:module';

import { sortObjectKeys } from './coverage-ledger.mjs';
import { resolveSourceSnapshot } from './source-snapshot.mjs';
import {
  auditSemanticCacheFields,
  isAcceptedLanguageAudit,
} from './semantic-language-audit.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pluginRoot = resolve(__dirname, '../..');

export const SEMANTIC_CACHE_VERSION = '2.0.0';
export const CANONICAL_CONTENT_LANGUAGE = 'en';
export const SEMANTIC_CACHE_FILE = 'semantic-cache.json';
export const SEMANTIC_LOCK_FILE = 'semantic.lock';
export const DEFAULT_LOCK_TTL_MS = 30_000;

/** The ONLY fields a semantic-cache entry may carry (spec Requirement
 *  "on-demand node-local semantic supplement": cacheable fields limited to
 *  the node/file's own summary, local tags, the hash it was generated
 *  against, and model/time provenance). Anything else — a cross-file
 *  conclusion, a business flow, answer text — is rejected outright.
 *
 *  `verification` (openspec: changes/full-semantic-isolation, capability
 *  `full-semantic-isolation`) is a minimal, additive extension: it is the
 *  Summary-Verifier's verdict ABOUT this entry's own `summary` — the same
 *  four-state field `verification-state.mjs` already governs for a
 *  knowledge-graph node — so Full mode's Summary-Verifier can record that
 *  verdict beside the cached summary it checked, without ever touching
 *  `knowledge-graph.json`. */
export const CACHEABLE_FIELDS = Object.freeze([
  'summary', 'tags', 'semanticSourceHash', 'model', 'generatedAt', 'verification',
]);

const REAL_FS = Object.freeze({
  existsSync, mkdirSync, readFileSync, writeFileSync, renameSync,
  openSync, writeSync, closeSync, unlinkSync,
});

/** Same two-step @excavator/core resolution every sibling script uses. */
async function resolveCore(root) {
  const require = createRequire(resolve(root, 'package.json'));
  try {
    return await import(pathToFileURL(require.resolve('@excavator/core')).href);
  } catch {
    return await import(pathToFileURL(resolve(root, 'packages/core/dist/index.js')).href);
  }
}

async function dataDirOf(projectRoot) {
  const { resolveDataDir } = await resolveCore(pluginRoot);
  return resolveDataDir(resolve(projectRoot));
}

// ---------------------------------------------------------------------------
// Read side — freshness is a pure identity + hash comparison, no I/O.
// ---------------------------------------------------------------------------

/**
 * @param {object|null|undefined} entry a semantic-cache entry, or absent
 * @param {string|null|undefined} currentContentHash the node's file's
 *   CURRENT content hash per `source-manifest.json` (see
 *   {@link currentSourceHashFor} for the same lookup this module's write-side
 *   CAS uses internally).
 * @param {string|object|null|undefined} cacheIdentity either the cache's
 *   `contentLanguage` value or the complete cache object. Passing the cache
 *   object also enforces the current schema version.
 * @returns {'fresh'|'missing'|'stale'|'noncanonical-language'}
 */
export function freshnessOf(entry, currentContentHash, cacheIdentity) {
  if (!entry || typeof entry.semanticSourceHash !== 'string' || entry.semanticSourceHash.length === 0) {
    return 'missing';
  }
  const canonicalIdentity = typeof cacheIdentity === 'string'
    ? cacheIdentity === CANONICAL_CONTENT_LANGUAGE
    : isCanonicalSemanticCache(cacheIdentity);
  if (!canonicalIdentity) return 'noncanonical-language';
  if (!isCanonicalSemanticCacheEntry(entry)) return 'noncanonical-language';
  if (typeof currentContentHash !== 'string' || currentContentHash.length === 0) return 'missing';
  return entry.semanticSourceHash === currentContentHash ? 'fresh' : 'stale';
}

/** Convenience boolean form of {@link freshnessOf} — `true` only for `'fresh'`. */
export function isFresh(entry, currentContentHash, cacheIdentity) {
  return freshnessOf(entry, currentContentHash, cacheIdentity) === 'fresh';
}

/** @param {object} cache a value returned by {@link readSemanticCache} */
export function lookupSemanticCacheEntry(cache, nodeId) {
  return cache?.entries?.[nodeId] ?? null;
}

export function isCanonicalSemanticCache(cache) {
  return cache?.version === SEMANTIC_CACHE_VERSION
    && cache?.contentLanguage === CANONICAL_CONTENT_LANGUAGE;
}

function emptyCache() {
  return {
    version: SEMANTIC_CACHE_VERSION,
    contentLanguage: CANONICAL_CONTENT_LANGUAGE,
    entries: {},
  };
}

function parseCache(raw) {
  const parsed = JSON.parse(raw);
  return {
    version: typeof parsed.version === 'string' ? parsed.version : '',
    ...(typeof parsed.contentLanguage === 'string' ? { contentLanguage: parsed.contentLanguage } : {}),
    entries: parsed.entries && typeof parsed.entries === 'object' ? parsed.entries : {},
  };
}

/** Read `dataDir/semantic-cache.json` off disk. Missing -> empty (never
 *  generated is not an error); corrupt -> also empty (reading a cache must
 *  never throw and block an answer, same as writing one). */
function readCacheFile(dataDir, fsImpl) {
  const cachePath = join(dataDir, SEMANTIC_CACHE_FILE);
  if (!fsImpl.existsSync(cachePath)) return emptyCache();
  try {
    return parseCache(fsImpl.readFileSync(cachePath, 'utf-8'));
  } catch {
    return emptyCache();
  }
}

/**
 * Read the full semantic cache for a project.
 * @param {string} projectRoot
 * @returns {Promise<{ version: string, contentLanguage?: string, entries: Record<string, object> }>}
 */
export async function readSemanticCache(projectRoot, { fsImpl = REAL_FS } = {}) {
  const dataDir = await dataDirOf(projectRoot);
  return readCacheFile(dataDir, fsImpl);
}

/** Read one file path's entry from `source-manifest.json` — the ground
 *  truth `contentHash` freshness/CAS is judged against.
 *  @returns {{ manifestExists: boolean, contentHash: string|null }} */
function readManifestEntry(dataDir, filePath, fsImpl) {
  const manifestPath = join(dataDir, 'source-manifest.json');
  if (!fsImpl.existsSync(manifestPath)) return { manifestExists: false, contentHash: null };
  let manifest;
  try {
    manifest = JSON.parse(fsImpl.readFileSync(manifestPath, 'utf-8'));
  } catch {
    return { manifestExists: false, contentHash: null };
  }
  const entry = (manifest.entries ?? []).find((e) => e.path === filePath);
  return { manifestExists: true, contentHash: entry?.contentHash ?? null };
}

/**
 * The node's file's CURRENT content hash, per `source-manifest.json`. `null`
 * means "freshness cannot be judged" (no manifest yet, or no entry for this
 * path) — a caller should treat that the same as `isFresh(...) === false`.
 */
export async function currentSourceHashFor(projectRoot, filePath, { fsImpl = REAL_FS } = {}) {
  const dataDir = await dataDirOf(projectRoot);
  return readManifestEntry(dataDir, filePath, fsImpl).contentHash;
}

// ---------------------------------------------------------------------------
// Field whitelist.
// ---------------------------------------------------------------------------

/** @param {object} fields @returns {{ ok: boolean, rejectedFields: string[] }} */
export function validateCacheableFields(fields) {
  const keys = Object.keys(fields ?? {});
  const rejectedFields = keys.filter((k) => !CACHEABLE_FIELDS.includes(k));
  if (typeof fields?.summary !== 'string' && !rejectedFields.includes('summary')) {
    rejectedFields.push('summary');
  }
  if (
    Object.hasOwn(fields ?? {}, 'tags')
    && (!Array.isArray(fields.tags) || fields.tags.some((tag) => typeof tag !== 'string'))
    && !rejectedFields.includes('tags')
  ) {
    rejectedFields.push('tags');
  }
  return { ok: rejectedFields.length === 0, rejectedFields };
}

/**
 * Read-side entry gate. `languageAudit` is writer-owned metadata rather than
 * a cacheable model field, so remove only that key before applying the same
 * allowlist/type rules used by the writer. The audit must then bind to the
 * exact current prose bytes; pre-digest and mutated entries are noncanonical.
 */
export function isCanonicalSemanticCacheEntry(entry) {
  if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return false;
  const { languageAudit, ...fields } = entry;
  if (!validateCacheableFields(fields).ok) return false;
  return isAcceptedLanguageAudit(
    languageAudit,
    auditSemanticCacheFields({ fields }),
  );
}

// ---------------------------------------------------------------------------
// Lock — shared `.excavator/semantic.lock`, held only briefly around commit.
// A stale lock (older than `ttlMs`) is stolen rather than blocked on forever;
// a live lock is NOT waited on by default (`maxAttempts: 1`) — a rejected
// write is an accepted, visible "not cached this turn", never a hang.
// ---------------------------------------------------------------------------

function lockPathOf(dataDir) {
  return join(dataDir, SEMANTIC_LOCK_FILE);
}

function readLockPayload(path, fsImpl) {
  try {
    return JSON.parse(fsImpl.readFileSync(path, 'utf-8'));
  } catch {
    return null;
  }
}

/** @returns {{ acquired: boolean, stolen: boolean }} */
function acquireLock(dataDir, { pid, host, now, ttlMs, maxAttempts, fsImpl }) {
  const path = lockPathOf(dataDir);
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const payload = JSON.stringify({ pid, host, acquiredAt: new Date(now()).toISOString() });
    try {
      const fd = fsImpl.openSync(path, 'wx'); // exclusive create — fails if the lock already exists
      fsImpl.writeSync(fd, payload);
      fsImpl.closeSync(fd);
      return { acquired: true, stolen: false };
    } catch (err) {
      if (err.code !== 'EEXIST') throw err;
      const existing = readLockPayload(path, fsImpl);
      const acquiredAtMs = existing?.acquiredAt ? Date.parse(existing.acquiredAt) : NaN;
      const stale = existing === null || Number.isNaN(acquiredAtMs) || (now() - acquiredAtMs) > ttlMs;
      if (stale) {
        // TTL-steal: best-effort overwrite of an abandoned (crashed-holder)
        // lock. Not perfectly race-free against a simultaneous stealer —
        // design D5 explicitly accepts this trade-off ("locks only
        // coordinate writes, not generation").
        fsImpl.writeFileSync(path, payload, 'utf-8');
        return { acquired: true, stolen: true };
      }
      // A live holder — no blocking retry within a single call by default
      // (maxAttempts: 1); the caller treats this as a rejected write.
    }
  }
  return { acquired: false, stolen: false };
}

function releaseLock(dataDir, fsImpl) {
  try {
    fsImpl.unlinkSync(lockPathOf(dataDir));
  } catch {
    // Already gone (or acquisition itself never succeeded) — fine.
  }
}

// ---------------------------------------------------------------------------
// Atomic write — temp file + rename, cleaning up the temp file on any
// failure so a failed commit never leaves a stray `.tmp-*` file behind.
// ---------------------------------------------------------------------------

function atomicWriteJson(finalPath, data, fsImpl) {
  const tmpPath = `${finalPath}.tmp-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  fsImpl.writeFileSync(tmpPath, JSON.stringify(data, null, 2), 'utf-8');
  try {
    fsImpl.renameSync(tmpPath, finalPath);
  } catch (err) {
    try { fsImpl.unlinkSync(tmpPath); } catch { /* best-effort cleanup */ }
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Commit.
// ---------------------------------------------------------------------------

/**
 * Commit one node's semantic-cache entry. Never throws.
 *
 * @param {{
 *   projectRoot: string,
 *   nodeId: string,
 *   filePath: string,
 *   fields: { summary: string, tags?: string[], semanticSourceHash: string, model?: string, generatedAt?: string },
 *   now?: () => number, ttlMs?: number, pid?: number, host?: string,
 *   maxLockAttempts?: number, fsImpl?: object,
 * }} args
 * @returns {Promise<{ ok: boolean, status: string, [key: string]: any }>}
 *   `status` is one of: 'committed' | 'rejected-fields' | 'noncanonical-language' | 'missing-source-hash'
 *   | 'invalid-args' | 'lock-held' | 'manifest-missing' | 'path-not-in-manifest'
 *   | 'stale-hash' | 'io-error'.
 */
export async function commitSemanticCacheEntry({
  projectRoot,
  nodeId,
  filePath,
  fields,
  now = () => Date.now(),
  ttlMs = DEFAULT_LOCK_TTL_MS,
  pid = process.pid,
  host = hostname(),
  maxLockAttempts = 1,
  fsImpl = REAL_FS,
} = {}) {
  try {
    if (typeof nodeId !== 'string' || nodeId.length === 0) {
      return { ok: false, status: 'invalid-args', error: 'nodeId is required' };
    }
    if (typeof filePath !== 'string' || filePath.length === 0) {
      return { ok: false, status: 'invalid-args', error: 'filePath is required' };
    }

    // Field whitelist — checked before touching the lock at all: a rejected
    // write is a no-op, not a partially-started one.
    const validation = validateCacheableFields(fields);
    if (!validation.ok) {
      return { ok: false, status: 'rejected-fields', rejectedFields: validation.rejectedFields };
    }
    let languageAudit = auditSemanticCacheFields({ fields });
    if (!isAcceptedLanguageAudit(languageAudit)) {
      // Source-owned non-Latin text may pass only through a current
      // SourceSnapshot. Restrict the authority to this node's file: the
      // cache entry is node-local, so an unrelated file cannot authorize a
      // model-authored span. The model patch has no exemption input here.
      try {
        const sourceSnapshot = resolveSourceSnapshot(projectRoot);
        languageAudit = auditSemanticCacheFields({
          fields,
          sourceSnapshot,
          sourcePaths: [filePath],
        });
      } catch {
        // No current snapshot means no source-owned exemption. Preserve the
        // deterministic rejected buckets from the authority-free audit.
      }
    }
    if (!isAcceptedLanguageAudit(languageAudit)) {
      return {
        ok: false,
        status: 'noncanonical-language',
        rejectedFields: languageAudit.rejected.map((entry) => entry.fieldPath),
        languageAudit,
      };
    }
    if (typeof fields?.semanticSourceHash !== 'string' || fields.semanticSourceHash.length === 0) {
      return { ok: false, status: 'missing-source-hash' };
    }

    const dataDir = await dataDirOf(projectRoot);
    fsImpl.mkdirSync(dataDir, { recursive: true });

    const lock = acquireLock(dataDir, { pid, host, now, ttlMs, maxAttempts: maxLockAttempts, fsImpl });
    if (!lock.acquired) return { ok: false, status: 'lock-held' };

    try {
      // Reload the latest manifest and compare-and-swap on the node's
      // CURRENT source hash (spec: "reject a stale-hash write, changing
      // nothing").
      const { manifestExists, contentHash: currentHash } = readManifestEntry(dataDir, filePath, fsImpl);
      if (!manifestExists) return { ok: false, status: 'manifest-missing' };
      if (currentHash === null) return { ok: false, status: 'path-not-in-manifest' };
      if (currentHash !== fields.semanticSourceHash) {
        return { ok: false, status: 'stale-hash', currentSourceHash: currentHash };
      }

      // Reload the latest cache too — a concurrent writer's OTHER node
      // entries must survive a merge, never be clobbered by a blind
      // overwrite (spec: "no lost update").
      const latest = readCacheFile(dataDir, fsImpl);
      // A cache with an old schema or missing/non-English identity is an
      // untrusted empty view. The first canonical write must never carry its
      // unaudited entries forward.
      const reusableEntries = isCanonicalSemanticCache(latest)
        ? Object.fromEntries(
          Object.entries(latest.entries).filter(([, entry]) => isCanonicalSemanticCacheEntry(entry)),
        )
        : {};
      const nextEntries = sortObjectKeys({
        ...reusableEntries,
        [nodeId]: { ...fields, languageAudit },
      });
      const nextCache = {
        version: SEMANTIC_CACHE_VERSION,
        contentLanguage: CANONICAL_CONTENT_LANGUAGE,
        entries: nextEntries,
      };

      atomicWriteJson(join(dataDir, SEMANTIC_CACHE_FILE), nextCache, fsImpl);
      return { ok: true, status: 'committed', languageAudit };
    } finally {
      releaseLock(dataDir, fsImpl);
    }
  } catch (err) {
    return { ok: false, status: 'io-error', error: err?.message ?? String(err) };
  }
}

export default {
  SEMANTIC_CACHE_VERSION,
  CANONICAL_CONTENT_LANGUAGE,
  SEMANTIC_CACHE_FILE,
  SEMANTIC_LOCK_FILE,
  DEFAULT_LOCK_TTL_MS,
  CACHEABLE_FIELDS,
  freshnessOf,
  isFresh,
  isCanonicalSemanticCache,
  lookupSemanticCacheEntry,
  readSemanticCache,
  currentSourceHashFor,
  validateCacheableFields,
  isCanonicalSemanticCacheEntry,
  auditSemanticCacheFields,
  isAcceptedLanguageAudit,
  commitSemanticCacheEntry,
};
